server:
  port: 8080

hc:
  device:
    ip: 192.168.1.65 # 人脸设备地址
    port: 8000
    login: admin
    password: ai20082018
  local:
    host: 192.168.1.106 #本机地址
    port: 7200

ai:
  local:
    host: 192.168.1.10 #ai_local地址
    port: 9090